arb-dir: lib/l10n
template-arb-file: en.arb
nullable-getter: false
output-localization-file: app_localizations.dart
output-class: AppLocalizations
untranslated-messages-file: untranslated_messages.json
generate: true