name: atwoz_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  go_router: ^14.6.2
  dio: ^5.7.0
  retrofit: ^4.4.1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  flutter_secure_storage: ^4.2.1
  riverpod_annotation: ^2.6.1
  flutter_screenutil: ^5.9.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  freezed: ^2.5.7
  path_provider: ^2.1.5
  flutter_svg: ^2.0.16
  arb_merger: ^0.0.2
  zooper_flutter_encoding_utf16: ^0.0.1
  gap: ^3.0.1
  infinite_scroll_pagination: ^4.1.0
  table_calendar: ^3.1.3
  file_picker: ^8.1.6
  cached_network_image: ^3.4.1
  fluttertoast: ^8.2.10
  permission_handler: ^11.3.1
  image_picker: ^1.1.2
  url_launcher: ^6.3.1
  riverpod: ^2.6.1
  hooks_riverpod: ^2.6.1
  rxdart: ^0.28.0
  in_app_update: ^4.2.3
  package_info_plus: ^8.1.2
  flutter_native_splash: ^2.4.3
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_generator: ^2.6.3
  build_runner: ^2.4.14
  retrofit_generator: ^9.1.5
  go_router_builder: ^2.7.1
  json_serializable: ^6.9.0
  riverpod_lint: ^2.6.3
  custom_lint: ^0.7.0
  hive_generator: ^2.0.1
  

arb_merger:
  supported_locales: ["en", "ko"]
  input_filepath: "lib/l10n"


# rps run
# rps gen


flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/fonts/
    - assets/images/

    
scripts:
run:
  $before: flutter pub get
  $script: flutter run
gen:
  build: dart run build_runner build --delete-conflicting-outputs
  watch: dart run build_runner watch --delete-conflicting-outputs


# dart run flutter_native_splash:create
flutter_native_splash:
  image: "assets/images/logo.png"
  # dark_image: ""
  # background_image: ""
  color: "#FFFFFF" # 기본 배경 색상"#000000" # 다크 모드 배경 색상
  android: true
  ios: true   
    # android_12:
  #   image: ""
  #   image_dark: ""

# TODO: 앱 아이콘 설정하기
# flutter_icons:
#   android: true
#   ios: true
#   image_path_android: ""
#   image_path_ios: ""